[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = "My Python Project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

#[tool.poetry.packages]
#[{include = "pythonproject", from = "src"}]

#[tool.poetry]
#package-mode = false

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.lint.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
python_version = "3.8"
warn_return_any = true
disallow_untyped_defs = true



